= Refactoring Trivia Legacy Code Kata

Show attempts to refactor link:https://github.com/jbrains/trivia[Trivia Legacy Code].
Tests created via link:https://approvaltests.com/[Approval Test Library].

If you are working in a legacy code scenario you should definitely check out link:https://www.youtube.com/watch?v=zyM2Ep28ED8[Introducing the Gilded Rose kata and writing test cases using Approval Tests by Emily Bache].

If you are looking for a simpler example to get started with testing legacy code, take a look at link:https://github.com/Richargh/legacy-code-test-starter-mvn-java[Legacy Code Starter].
If you are looking for an example that does not use approval tests, see link:https://github.com/johanneswseitz/trivia-with-golden-master-java[Trivia with Golden Master].

== Attempts

* link:original/[Original Trivia] with added approval tests
* link:attempt01/[Attempt 01], a refactoring trying to use mostly extract method
* link:attempt011/[Attempt 01.1], a refactoring building on top of Attempt 01, now trying to extract everything to classes that was a method before

== Features

* link:.sdkmanrc[Java 17]
* link:https://approvaltests.com/[Approval Tests]
* Multiple JPMS Modules, one for each attempt

== Preconditions

* Install the right java version.
  ** If you have link:https://sdkman.io/[SDK Man] installed, call `sdk use env` to install the version from link:.sdkmanrc[.sdkmanrc]
* Have Maven installed

== Usage

* `mvn test`

== Leagcy Code Katas

* link:https://github.com/jbrains/trivia[Trivia]
* link:https://github.com/emilybache/GildedRose-Refactoring-Kata[Gilded Rose]


